var GAME_LEVELS = [
["                                                             yyy                   ",
 "                                                           yy                      ",
 "                                                           yyy                     ",
 "                                                                                   ",
 "                                    y                                              ",
 "                                   yy                                              ",
 "             y                                           xxx          xxx          ",
 "            yyyyyy                                  x!!!! xxx                      ",
 "             yyyy           xxx                  xx  vvvv            x!!!xx        ",
 "                                           xx            y                  xxx    ",
 "            y           xx                             yy y                    x   ",
 "  xx      yyy             xxx                                                     x",
 "  x                              xxx                                               ",
 "  x                            xx                                               o  ",
 "  x                  xx    xx                                              t       ",
 "  x  @             xx                                        xxxxx       ttt       ",
 "  xxxxxxxxxxxx!!!xxxxxxxxxxxxxxx   xxxxxxx                 xxxxxxx      xxxxxxxxxxx",
 "                              x   x     x              !!!!!x         xx           ",
 "                              x!!!x     x              !!!!!x    xx                ",
 "                              x!!!x     x !!!xx!!!!    !xxxxx         xx           ",
 "                              x!!!x     x                           xx             ",
 "                               !!!         x xxxxxxx              xxx              ",
 "                               !!!                 xx xxxxxxxxxxxxxxxxxxxx         ",
 "                               !!!                                                 "],
  ["                                                                                      ",
   "  yyy                                                                                 ",
   "   yy                              xxvvxx                                             ",
   "                                   xxvvxx                                             ",
   "                                                         xxxx                         ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   "                                                 x!!!!x                               ",
   "                            yyyyyy                                                    ",
   "               xxxxx         yyyy                                                     ",
   "                                                  xxxx                                ",
   "  xx                                                                                  ",
   "  x                                                        yyyy                       ",
   "  x                                                                                   ",
   "  x                                         xxxx             xxx   =   xxx            ",
   "  x            xx|xx                        xxxx             xxx   o   xxx            ",
   "  x            x  xx                        xxxx             xxx       xxx            ",
   "  x    @       x  xx        xxxxxxxxxxx                      xxx       xxx            ",
   "  xxxxxxxxxxxxxx  x x!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                     !!!!!!!!!!!!!!!!!!!!!!        !!!!!!!                            ",
   "                     !!!!!!!!!!!!!!!!!!!!!!        !!!!!!!                            ",
   "                                                                                      "],
  ["                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "       yyy          yyy     yyyyyyyyy      yyy          yyy                                    ",
   "       yyy   yyy    yyy     yyy    yyy     yyy   yyy    yyy                                    ",
   "       yyy   yyy    yyy     yyy    yyy     yyy   yyy    yyy                                    ",
   "       yyyyyyy  yyyyyyy      yyyyyyyy      yyyyyyy  yyyyyyy                                    ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               ",
   "               xxxvvvvvxxxx           xxxxxxxvvvvvxxxxx                                        ",
   "                                                                  t                            ",
   "                                                                  t                            ",
   "                                                                  t                            ",
   "                                                                  t                            ",
   "                                yy                       xxxxxxxxxt                            ",
   "                               yyyy                      t     vv                              ",
   "                                          xxxxxxxxx      t                                     ",
   "                         xxxxvvvvvxxxx        |          t                                     ",
   "                                                         t                    o                ",
   "                                                         t                                     ",
   "                                            xxxxxx       t                                     ",
   "  xx           xxxxxxx                         =                xxxxxxxxxxxxxxxxxxxx           ",
   "  x                                                                                            ",
   "  x                                                                                            ",
   "  x    @                 xxxxxxxxxxx                                                           ",
   "  xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx  ",
   "                                                                                               ",
   "                                                                                               ",
   "                                                                                               "],
  ["                                                                                                                                  ",
   "               yyyy                                                                                                               ",
   "                yy              yyy                                                                                               ",
   "                               yyyyy                                                                                   o          ",
   "        @  $                                                                                                                      ",
   "       xxxxxx                  xxxxxx    xxxxxx    xxxxxx xx      |   xxttxx    xxxxxx xx       =   xxxxxx    !!!!!! xxxx         ",
   "       xxxxxx         |        xxxxxx  | xxxxxx    xxxxxx   !!    =   xxxxxx    xxxxxx   !!      |  xxxxxx    xxxxxx     xxx      ",
   "       xxxxxx       !xx!       xxxxxx    xxxxxx    xxxxxx     xx      xxxxxx    xxxxxx     xx       xxxxxx    xxxxxx    xx        ",
   "       xxxxxx      xxxxxx      xxxxxx    xxxxxx    xxxxxx       xx    xxxxxx    xxxxxx       xx     xxxxxx    xxxxxx xxx          ",
   "       xxxxxx xxxxx      xxxxx xxxxxx    xxxxxx    xxxxxx        !!   xxxxxx    xxxxxx         !!   xxxxxx    xxxxxx   xxx        ",
   "       xxxxxxxxxxxx      xxxxxxxxxxxx    xxxxxx    xxxxxx          xx xxxxxx    xxxxxx           xx xxxxxx    xxxxxx     xxx      ",
   "                                                                                                                                  ",
   "                                        yyyy                                               yyyy                                   ",
   "                                         y                                             yyyyyy                                     ",
   "                                          y                                                                                       ",
   "                                                                                                yyy                               ",
   "                                                                                                                                  ",
   "                                                                                                                                  ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "                                                                                                                                  ",
   "                                                                                                                                  ",
   "                                                                                                                                  ",
   "                                                                                                                                  ",
   "                                                                                                                                  ",
   "                                                                                                                                  ",
   "                                                                                                                                  "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
